# -*- coding: utf-8 -*-
"""api_extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sGTdUg9KF7AamVA_fQz6P2lijxQsoHIr
"""

#chahrazed : arabic sentiment analysis with api 
#libraiies 
import re
import tweepy
from tweepy import OAuthHandler

# keys and tokens from the Twitter Dev Console 
consumer_key = '9sbiaw8LE9JD8z3xLm1q18gN6'
consumer_secret = 'NA7mz0NWIvzhZgwxtVqBIxorLMRLJy9VCbSqZqOG79mKddj0f2'
access_token = '1291368045592686593-k5J6P77O6GTm9GDdw1gfX6xLiXSgET'
access_token_secret = 'gMtPbmyBwgjRUrH48phJvEtbVcFCGMJFvaq1vtT4njeEQ'

# twitter authentification
try:
  # create OAuthHandler object
  auth = OAuthHandler(consumer_key, consumer_secret) 
  # set access token and secret 
  auth.set_access_token(access_token, access_token_secret) 
  # create tweepy API object to fetch tweets 
  api = tweepy.API(auth)
except:
  print("Error: Authentication Failed")

def get_tweets(name):
  n=140 #we take 140 caracteres 
  public_tweet=api.search(name)
  for tweet in public_tweet:
    if (len(tweet.text)<=n):
      print(tweet.text)

#print(get_tweets("الجزائر"))

def get_tweets_listes(name):
  n=140 #we take 140 caracteres
  liste=[] 
  public_tweet=api.search(name)
  for tweet in public_tweet:
    if (len(tweet.text)<=n):
      liste.append(tweet.text)
  return liste    

#print(get_tweets_listes("الجزائر"))

import pandas as pd
from pandas import DataFrame
def data_to_df(name):
  import pandas as pd
  from pandas import DataFrame
  df = DataFrame (get_tweets_listes(name),columns=['comments'])
  return df
#print(data_to_df("الجزائر").head())

def data_to_csv(name):
  df = DataFrame(get_tweets_listes(name),columns=['comments'])
  return (df.to_csv("{}.csv".format(name),index=False))

#print(data_to_csv("الجزائر"))





